# fly.toml app configuration file generated for mordle on 2023-06-15T21:28:35+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mordle"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[build.args]
  REACT_APP_SERVER_HOSTNAME="mordle-server.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
