services:
  - type: web
    plan: free
    name: mordle
    runtime: docker
    region: singapore
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    envVars:
      - key: PORT
        value: 3000
      - key: REACT_APP_SERVER_HOSTNAME
        fromService:
          type: web
          name: server
          envVarKey: RENDER_EXTERNAL_HOSTNAME

  - type: web
    plan: free
    name: server
    runtime: docker
    region: singapore
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    envVars:
      - key: PORT
        value: 4000
      - key: MIX_ENV
        value: prod
      - key: PHX_SERVER
        value: true
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: CLIENT_HOSTNAME
        fromService:
          type: web
          name: mordle
          envVarKey: RENDER_EXTERNAL_HOSTNAME