services:
  - type: web
    plan: free
    name: client
    runtime: docker
    region: singapore
    dockerfilePath: ./client/Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: REACT_APP_API_URL
        value: http://localhost:4000/api
      - key: REACT_APP_WS_URL
        value: ws://localhost:4000/socket

  - type: web
    plan: free
    name: server
    runtime: docker
    region: singapore
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: PORT
        value: 4000
      - key: MIX_ENV
        value: prod
      - key: PHX_SERVER
        value: true
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PHX_HOST
        value: mordle.onrender.com