# fly.toml app configuration file generated for mordle-server on 2023-08-29T20:01:03+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mordle-server"
primary_region = "sin"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  CLIENT_HOSTNAME = "mordle0.vercel.app"
  PORT = 4000